### ISSUE TITLE
AddQueryParameters, in RequestInformation, is not adding parameters beginning with a capital to the URI

### ISSUE THREAD

**Issue by timandella** [microsoft/kiota-abstractions-dotnet#127] opened 2023-09-22 12:56 UTC
I am using Microsoft Kiota to generate an API client from an open api yaml file. In this file, one of the request parameters uses Pascal case
```
- name: TenantId
  in: query
  required: true
  schema:
    type: string
```
This was working fine when the generated API client was using version 1.3.1 of Microsoft.Kiota.Abstractions. However, when upgrading to 1.3.2, the generated uri is not including the parameter at all, which results in an error when the API is called as that parameter is required.

Here is a sample C# console app (target framework net7.0, running on Windows 10), using code I extracted from the generated API client
```
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Authentication;
using Microsoft.Kiota.Http.HttpClientLibrary;

namespace Kiota;

public class Program
{
    static void Main(string[] args)
    {
        var pathParameters = new Dictionary<string, object>
        {
            { "baseurl", "http://localhost:123" }
        };
        var requestAdapter = new HttpClientRequestAdapter(new AnonymousAuthenticationProvider())
        {
            BaseUrl = "http://localhost:123"
        };
        var requestBuilder = new TestRequestBuilder(pathParameters, requestAdapter);

        var queryParms = new TestRequestBuilder.TestRequestBuilderGetQueryParameters
        {
            TenantId = Guid.NewGuid().ToString()
        };

        var requestInfo = requestBuilder.ToGetRequestInformation(x => x.QueryParameters = queryParms);
        Console.Write(requestInfo.URI.ToString());
    }
}

public class TestRequestBuilder : BaseRequestBuilder
{
    public TestRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/Test{?TenantId*}", pathParameters)
    {
    }

    public class TestRequestBuilderGetQueryParameters
    {
        public string TenantId { get; set; }
    }

    public class TestBuilderGetRequestConfiguration
    {
        public RequestHeaders Headers { get; set; }
        public IList<IRequestOption> Options { get; set; }
        public TestRequestBuilderGetQueryParameters QueryParameters { get; set; } = new TestRequestBuilderGetQueryParameters();

        public TestBuilderGetRequestConfiguration()
        {
            Options = new List<IRequestOption>();
            Headers = new RequestHeaders();
        }
    }

    public RequestInformation ToGetRequestInformation(Action<TestBuilderGetRequestConfiguration>? requestConfiguration = default)
    {
        var requestInfo = new RequestInformation
        {
            HttpMethod = Method.GET,
            UrlTemplate = UrlTemplate,
            PathParameters = PathParameters,
        };
        requestInfo.Headers.Add("Accept", "application/problem+json");
        if (requestConfiguration != null)
        {
            var requestConfig = new TestBuilderGetRequestConfiguration();
            requestConfiguration.Invoke(requestConfig);
            requestInfo.AddQueryParameters(requestConfig.QueryParameters);
            requestInfo.AddRequestOptions(requestConfig.Options);
            requestInfo.AddHeaders(requestConfig.Headers);
        }
        return requestInfo;
    }
}
```
With 1.3.1, the uri is generated as http://localhost:123/api/v1/Test?TenantId=8d20c652-1466-444f-af2a-403a03476187

With 1.3.2 the uri is generated as http://localhost:123/api/v1/Test

Note: If I change all instances of "TenantId " to "tenantId" in the above code, then it works successfully (although this is not really a satisfactory fix as we don't really want to change the original API).

**Comment by baywet** [comment] 2023-09-22 13:53
Thanks for using kiota and for reporting this @timandella

This is caused by this normalization

https://github.com/microsoft/kiota-abstractions-dotnet/blob/f557db3df850d28e88a28ee8a1d9cdecbc95c712/src/RequestInformation.cs#L112

In my opinion it should not be here anymore (ToFirstCharacterLowerCase) since kiota is now generating an attribute with the right name as soon as the property name differs from the parameter name.

But I'd like the opinion of @andrueastman and @andreaTP before we proceed to any change here.

**Comment by andreaTP** [comment] 2023-09-22 14:11
I agree @baywet , I might have missed it when moving to Std.UriTemplate, from a first look, seems like a leftover from the previous case-insensitive logic.

**Comment by baywet** [comment] 2023-09-22 16:49
Thanks for the confirmation. @timandella is this something you'd be willing to submit a pull request for?

**Comment by timandella** [comment] 2023-09-23 13:55
I tried to create a pull request, but GitHub desktop tells me I don't have write access to push up my local commit

**Comment by andreaTP** [comment] 2023-09-23 14:05
@timandella the usual process is:
- fork the repo
- push to a new branch in your fork
- open a PR to the official one

Let me know if I should give you more detailed instructions, but I think you can find some good material online on how to open a first PR.

**Comment by timandella** [comment] 2023-09-23 14:25
Thanks. It's my first ever pull request - https://github.com/microsoft/kiota-abstractions-dotnet/pull/129

**Closed** 2023-09-24 13:50 UTC
Labels: bug, help wanted, WIP

**Comment by SilverioMiranda** [comment] 2024-05-13 03:50
@baywet 

This change broke any new use of kiota that have properties using lower case for name of properties because  Kiota generation properties will be always PascalCase and the requestInfo.AddQueryParameters(requestConfig.QueryParameters) will be always adding PascalCase QueryParameter to the Dictionary and when the query parameter is lower_case or camelCase this will break the request not sending those parameters.

**Comment by SilverioMiranda** [comment] 2024-05-13 03:53
Steps to reproduce : Make an api with query parameter [FromQuery] string? name and generate the client sdk with kiota and try to use. doesnt work and dont give any fuck*** warning that the property was missing or the case is not (wrong)expected

And this also break the use of services.AddRouting(o => { o.LowercaseQueryStrings = true; o.LowercaseUrls = true; }); in any aspnetcore api

**Comment by andreaTP** [comment] 2024-05-13 09:40
@SilverioMiranda here you are commenting on an issue closed about 8 months ago.
Please, feel free to open a new one if you are still facing a problem.

While doing it, I encourage you to improve the effectiveness of your communication by:
- verify the kiota version you are using
- add a minimal reproducer of the issue ( maybe you can start from [this example](https://github.com/microsoft/kiota/blob/main/tests/Kiota.Builder.IntegrationTests/GeneratesUritemplateHints.yaml) )
- use appropriate wording for a public forum

Thanks in advance :pray:
